<?php

function  uf_util_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_profile_form': 
  	 $form['account']['#access'] = FALSE;
     $form['social_media_group'] = array(
        '#type' => 'fieldset',
        '#title' => t('Social Media'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );
     $social_fields = array(
        'field_twitter',
        'field_facebook',
        'field_linkedin',
        'field_github',
      );

     foreach($social_fields as $field) {
        $form['social_media_group'][$field] = $form[$field];
        unset($form[$field]);
     } 

     $form['field_user_skill']['skill_legend'] = array(
      '#markup' => '<div class="row">
                        <div id="skill_legend">
                          <h3 class="skill_name col-sm-2">Skill Guide</h3>
                          <div class="sr-only">
                            <ul>
                              <li>Level 1: Little to no knowledge</li>
                              <li>Level 2: Beginner Skill Level</li>
                              <li>Level 3: Limited Knowledge</li>
                              <li>Level 4: Competent User</li>
                              <li>Level 5: Team Contributor</li>
                              <li>Level 6: Team Leader</li>
                              <li>Level 7: Myplanet Contributor</li>
                              <li>Level 8: Myplanet Leader</li>
                              <li>Level 9: Industry Contributor</li>
                              <li>Level 10: Industry Leader</li>
                            </ul>
                          </div>
                          <div class="progress" id="legend">
                            <div class="progress-bar guidebar" style="width: 10%" popover="Little to no knowledge" popover-trigger="mouseenter"><span>1</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Beginner Skill Level" popover-trigger="mouseenter"><span>2</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Limited Knowledge" popover-trigger="mouseenter"><span>3</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Competent User" popover-trigger="mouseenter"><span>4</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Team Contributor" popover-trigger="mouseenter"><span>5</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Team Leader" popover-trigger="mouseenter"><span></span>6</div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Myplanet Contributor" popover-trigger="mouseenter"><span>7</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Myplanet Leader" popover-trigger="mouseenter"><span>8</span></div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Industry Contributor" popover-trigger="mouseenter">9</div>
                            <div class="progress-bar guidebar" style="width: 10%" popover="Industry Leader (El Jefe!)" popover-trigger="mouseenter"><span>10</span></div>
                          </div>
                        </div>
                      </div>',               
      );
    break;
    case 'user_login_block':
     $form['name']['#access'] = FALSE;
     $form['pass']['#access'] = FALSE;
     $form['actions']['#access'] = FALSE;
     $form['links']['#access'] = FALSE;
    break;
  }

}