<?php

/**
 * Implements hook_form_alter().
 */
function  uf_util_form_alter(&$form, &$form_state, $form_id) {

  dsm($form);
  switch ($form_id) {
    case 'user_profile_form':
  	 $form['account']['#access'] = FALSE;
     $form['social_media_group'] = array(
        '#type' => 'fieldset',
        '#title' => t('Social Media'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );
     $social_fields = array(
        'field_twitter',
        'field_facebook',
        'field_linkedin',
        'field_github',
      );

     foreach($social_fields as $field) {
        $form['social_media_group'][$field] = $form[$field];
        unset($form[$field]);
     }
     // Adding hints to the skill fields
     $form['field_user_skill']['und']['0']['field_skill']['und']['#description'] = 'One skill at a time please!';
     $form['field_user_skill']['und']['0']['field_user_skill_current_rating']['und']['#description'] = 'How good are you...';
     $form['field_user_skill']['und']['0']['field_user_skill_desired_rating']['und']['#description'] = '... and how good do you WANT to be?';
    // redirect on submit of user-profile edit
     array_push($form['#submit'], 'redirect_after_submit');

    break;
    case 'user_login_block':
     $form['name']['#access'] = FALSE;
     $form['pass']['#access'] = FALSE;
     $form['actions']['#access'] = FALSE;
     $form['links']['#access'] = FALSE;
    break;

    // disable preview button on project profile page
    case 'project_profile_node_form':
      $form['actions']['preview']['#access'] = FALSE;
    break;

    // disable preview button on team profile page
    case 'team_profile_node_form':
      $form['actions']['preview']['#access'] = FALSE;
    break;
  }

}

/**
 * Implements hook_user_login().
 */
function uf_util_user_login(&$edit, $account) {
  // Get all messages, particularly so we can squelch the gauth message.
  drupal_get_messages();
}

/**
 * Implements redirect on submit
 */
function redirect_after_submit(&$form, &$form_state){
  $form_state['redirect'] = 'user';
}
