<?php

/**
 * @file
 * Expose form submission to services.
 */

/**
 * Implements hook_services_resources().
 */
function uf_edit_services_resources() {
  return array(
    'uf_node' => array(
      'retrieve' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit', 'name' => 'includes/uf_node'),
        'help' => t('Retrieves node\'s form values.'),
        'callback' => '_uf_node_retrieve',
        'args' => array(
          array(
            'name' => 'form_id',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The form_id of the form',
          ),
          array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 1),
            'type' => 'int',
            'description' => 'The nid to edit',
          ),
        ),
        'access callback' => 'user_is_logged_in',
      ),
      'create' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit', 'name' => 'includes/uf_node'),
        'help' => t('Creates a node form submission.'),
        'callback' => '_uf_node_submit',
        'args' => array(
          array(
            'name' => 'form_id',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The form_id of the form',
          ),
          array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 1),
            'type' => 'int',
            'description' => 'The nid to edit',
          ),
          array(
            'name' => 'form_values',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The form data to submit',
            'type' => 'array',
          ),
        ),
        'access callback' => 'user_is_logged_in',
      ),
    ),
    'uf_user' => array(
      'retrieve' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit', 'name' => 'includes/uf_user'),
        'help' => t('Retrieves user form values.'),
        'callback' => '_uf_user_retrieve',
        'args' => array(
          array(
            'name' => 'uid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The uid to edit',
          ),
        ),
        'access callback' => 'user_is_logged_in',
      ),
      'create' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit', 'name' => 'includes/uf_user'),
        'help' => t('Creates a user edit form submission.'),
        'callback' => '_uf_edit_user_submit',
        'args' => array(
          array(
            'name' => 'uid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The uid to edit',
          ),
          array(
            'name' => 'form_values',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The form data to submit',
            'type' => 'array',
          ),
        ),
        'access callback' => 'user_is_logged_in',
      ),
    ),
    'uf_field' => array(
      'index' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit', 'name' => 'includes/uf_field'),
        'help' => t('Retrieves the options for "list" fields.'),
        'callback' => '_uf_field_retrieve',
        'args' => array(
          array(
            'name' => 'field_ids',
            'optional' => FALSE,
            'source' => array('param' => 'fields'),
            'type' => 'string',
            'description' => 'The field_id of the field.',
          ),
        ),
        'access callback' => 'user_is_logged_in',
      ),
    ),
  );
}
