<?php

/**
 * @file
 * Expose form submission to services.
 */

/**
 * Implements hook_services_resources().
 */
function uf_edit_services_resources() {
  return array(
    'uf_edit_submission' => array(
      'retrieve' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit'),
        'help' => t('Retrieves a node edit form array'),
        'callback' => '_uf_edit_retrieve',
        'args' => array(
          array(
            'name' => 'form_id',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The form_id of the form',
          ),
          array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 1),
            'type' => 'int',
            'description' => 'The nid to edit',
          ),
        ),
      ),
      'create' => array(
        'file' => array('type' => 'inc', 'module' => 'uf_edit'),
        'help' => t('Creates a node form submission'),
        'callback' => '_uf_edit_submit',
        'args' => array(
          array(
            'name' => 'form_id',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The form_id of the form',
          ),
          array(
            'name' => 'form_values',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The form data to submit',
            'type' => 'array',
          ),
        ),
      ),
    ),
  );
}
