<?php
/**
 * @file
 * This module allows a user to change their profile picture in place through a modal form.
 *
 * REQUIREMENTS
 * CTools
 *
 * OPTIONAL
 * jQuery Plugins, for a better tooltip
 *
 * INSTALLATION
 * No particular requirements
 *
 * USAGE
 * Enable the module.
 *
 * Make sure you create a default picture and that it displays on the user profile page if you want to allow users to upload their first
 * image as well.
 */
/**
 * Implement hook_menu()
 */
function profile_pic_changer_menu() {
  return array(
    'profile-pic-changer/edit/%' => array(
      'title'           => 'Update your profile picture',
      'page callback'   => 'profile_pic_changer_ajax',
      'page arguments'  => array(2),
      'access callback' => TRUE,
      'type'            => MENU_CALLBACK,
      'file'            => 'profile_pic_changer.pages.inc'
    )
  );
}

/**
 * Preprocessor for the user profile page.
 *
 * Make sure our javascript is in, which will capture a click on the user profile picture.
 */
function profile_pic_changer_preprocess_user_profile(&$variables) {
  global $user;
  if ($user->uid != $variables['user']->uid) {
    return;
  }

  if (!module_exists('ctools')) {
    drupal_set_message(t("CTools is required for the Profile Pic Changer module."), 'error');
    return;
  }

  ctools_include('modal');
  ctools_modal_add_js();

  // to add ctools integration
  drupal_add_js(drupal_get_path('module', 'profile_pic_changer') . '/js/profile-pic-changer.js');

  // add better tooltips if possible
  if (module_exists('jquery_plugin')) {
    drupal_add_library('jquery_plugin', 'tooltip');
    drupal_add_js(drupal_get_path('module', 'profile_pic_changer') . '/js/profile-pic-changer-tooltip.js');
    drupal_add_css(drupal_get_path('module', 'profile_pic_changer') . '/css/profile-pic-changer.css');
  }

  // add the modal class to the image's link element
  $markup = $variables['user_profile']['user_picture']['#markup'];
  $match  = array();
  $re     = "/(<a.*?>)/";
  if (preg_match($re, $markup, $match)) {
    $link = $match[1];
    $link = preg_replace("/href=\"[^\"]+\"/", "href='/profile-pic-changer/edit/" . $user->uid . "'", $link);
    $link = preg_replace("/title=\"[^\"]+\"/", "", $link);
    if (strstr($link, 'class')) {
      $link = preg_replace("/class=\"([^\"]+)\"/", 'class="$1 ctools-use-modal"', $link);
    }
    else {
      $link = str_replace(">", 'class="ctools-use-modal">', $link);
    }

    $markup = preg_replace($re, $link, $markup);
    $variables['user_profile']['user_picture']['#markup'] = $markup;
  }
}
